---
- hosts: all
  tasks:
    - name: install packages
      become: true
      become_user: root
      dnf:
        state: present
        name:
         - "@core"
         - "@Graphical Administration Tools"
         - "@Development Tools"
         - "@System Tools"
         - "@Server"
         - "@Network Servers"
         - s390utils-base
         - nfs-utils
         - sshpass
         - ansible-core
         - python3-pip
         - autofs
         - vim
